Fix Regexp.new ArgumentError on ruby 3.3
Ruby 3.2 introduced a deprecation of the third positional parameter for
encoding:
https://github.com/ruby/ruby/commit/7e8fa06022a9e412e3f8e6c8b6f0ba1909f648d5

The argument was then removed in Ruby 3.3:
https://github.com/ruby/ruby/commit/04cfb26bd394b8e92f24f18799f5e9fc96b2ea69

```
ArgumentError: wrong number of arguments (given 3, expected 1..2) (ArgumentError)

  USASCIIRegexp = Regexp.new("\\A#{us_ascii}*\\z", nil, 'n')
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```